import { Col, Row } from "react-bootstrap";
import styles from "./appshell.module.css";
const { default: Sidebar } = require("../Sidebar/Sidebar");
import Point from "@/components/elements/Point";
import Head from "next/head";

const AppShell = ({ children }) => {
    return (
        <>
            <Head>
                <title>Evander's Portfolio</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className={`${styles.container}`}>
                <div className={`${styles.background}`}></div>
                <Sidebar />
                <Point styles={`${styles.point}`} />
                <Row className={styles.row}>
                    <Col className={styles.children} lg={{ span: 8, offset: 2 }} md={{ span: 10, offset: 2 }} sm={{ span: 12, offset: 0 }}>
                        {children}
                    </Col>
                </Row>
            </div>
        </>
    );
};

export default AppShell;
